### ISSUE TITLE
Another protocol violations or bugs in FlashMQ

### ISSUE THREAD

**Issue by songxpu** [halfgaar/FlashMQ#104]
Hi @halfgaar, some findings still have not been reported in #103, so I have submitted this issue and apologize for any inconvenience caused.

Running command:
```
./FlashMQBuildRelease/flashmq -c /home/ubuntu/conf/flashmq.conf
```
**flashmq.conf:**
```
listen {
    protocol mqtt
    inet_protocol ip4
    inet4_bind_address 0.0.0.0
    port 1883
}

bridge {
    address 192.168.222.128
    port 1884
    tls off
    protocol_version mqtt5
    keepalive 600
    bridge_protocol_bit false
    publish topic 1
    subscribe topic 1
}

allow_anonymous true
log_file    /tmp/flashmq/flashmq.log
storage_dir /tmp/flashmq

```

**Comment by songxpu** [comment]
According to the specification of [MQTTv3.1.1](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/mqtt-v3.1.1.html) and [MQTTv5.0](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html):
```
[MQTT-3.1.0-1]
After a Network Connection is established by a Client to a Server, the first packet sent from the Client to the Server MUST be a CONNECT packet.
```
However, FlashMQ unexpectedly responded to any PINGREQ initiated by clients who had not yet established an MQTT connection with the broker, that is, the first request could be a PINGREQ message instead of a CONNECT, which violates protocol specification.
```
echo c000  | xxd -p -r | nc 172.17.0.5 1883
```
![image](https://github.com/halfgaar/FlashMQ/assets/44093631/9d1d601a-e56b-4ec3-8668-4279e97624ab)


Similarly, as defined by the specification, PINGREQ is sent from the client to the server.
However, this seems to be violated in bridged mode, where FlashMQ and the remotely bridged broker have the identities of client and server, respectively.
It is permissible behavior for FlashMQ to initiate a PINGREQ to the remote broker (IP 192.168.222.128) and receive a PINGRES.
However, I found that if the remote broker accidentally sends a PINGREQ message to FlashMQ and FlashMQ returns a PINGRESP, this seems to be a bug. 
I think this is essentially due to the mistake of treating the remote broker and the local client as the same identity, but essentially they are different.

![image](https://github.com/halfgaar/FlashMQ/assets/44093631/d4437bfe-c558-41ad-9cc3-12e4567aab1b)

**Comment by songxpu** [comment]
According to the specification of [MQTTv5.0](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html):
```
[MQTT-3.3.4-6] 
A PUBLISH packet sent from a Client to a Server MUST NOT contain a Subscription Identifier.
```
However, if we send such a packet:
```
echo 106100044d5154540540b3b037119afb60e317001901215c5326000f766e72366d4541644d78553c44327800173049574d36324268715a6179524b5a62536749534a31360013317675535434755733374e64397846585a38570008676235716d5836363554000841684b3146454962f71a16010109000c79a506aff5eef39ed5210cd60bba849b523155596942337761334c376e765936573739413862666a46414e4e3172647544345773415778724a6667386d3258653363 | xxd -p -r | nc 172.17.0.5 1883
```
FlashMQ unexpectedly returned a response instead of rejecting such a request.
![image](https://github.com/halfgaar/FlashMQ/assets/44093631/25c98a5f-8bac-451b-91ec-303ae9e585aa)

**Comment by songxpu** [comment]
According to the specification of [MQTTv5.0](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html):
```
[MQTT-3.4.2-1] 
The Client or Server sending the PUBACK packet MUST use one of the PUBACK Reason Codes.

# note that Table 3‑4  define the PUBACK Reason Codes.
```
However, if we send such a PUBACK (with invalid reason codes like 0x01) to FlashMQ, FlashMQ seems to have received such messages normally.
```
# the packet contain CONNECT -> PUBACK -> PUBLISH (QoS1)
echo 10800100044d51545405c20001411701212e3b22464426001a5a554c7742485a7a676a6e6579664f77447230496a374a46304c001a38436f4c643657616b6a6a4e74306c436b6f78536b593143356c001b6d6c33456b677234313272796d6d707a5a7664534e6c735965594200086732514e52776a38000b4743684f424f6c7a7967624004b65d0100320f0005746f706963000100746f706963  | xxd -p -r | nc 172.17.0.5 1883
```
The response is CONACK->PUBACK, which proves that the FlashMQ received PUBACK was not rejected as expected.

![image](https://github.com/halfgaar/FlashMQ/assets/44093631/df64145e-e288-4880-9fcb-3a2a68913e0b)

**Comment by halfgaar** [comment]
> Hi @halfgaar, some findings still have not been reported in #103, so I have submitted this issue and apologize for any inconvenience caused.

No apologies necessary. I just didn't know you weren't done. I'm OK with you opening a separate issue per finding to avoid that problem.

Anyway, fixes are underway. I'll push some code soon.

Some open up some considerations. Like the invalid puback code. FlashMQ doesn't actually do anything with it; the only thing it can do is clear the message from the queue, which it must do always. Checking it would just add overhead to a potentially hot path of the code. :thinking:

**Comment by bigsmoke** [comment]
> According to the specification of [MQTTv5.0](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html):
> 
> […]

I don't understand why and who marked [this](https://github.com/halfgaar/FlashMQ/issues/104#issuecomment-2107364232) excellent, well-written comment by @songxpu as “abuse”. I know for a fact that @halfgaar _loves_ to receive such detailed bug reports. Excellent stuff, @songxpu! 👏

**Comment by halfgaar** [comment]
I addressed most of the issues in this branch: https://github.com/halfgaar/FlashMQ/tree/more-protocol-fixes

It's not final yet.

Currently, two are in an undecided state:

* Sending `PINGRESP` even when it's a client/bridge. It doesn't really do harm, and the spec doesn't say it's a protocol error? I've seen weirder BTW. I've seen websocket clients that decide on their own to send pongs ...
* The puback response code is currently still ignored. I just kind of dislike having to parse it merely for checking the protocol violation.

**Comment by JaylinYu** [comment]
> > According to the specification of [MQTTv5.0](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html):
> 
> > 
> 
> > […]
> 
> 
> 
> I don't understand why and who marked [this](https://github.com/halfgaar/FlashMQ/issues/104#issuecomment-2107364232) excellent, well-written comment by @songxpu as “abuse”. I know for a fact that @halfgaar _loves_ to receive such detailed bug reports. Excellent stuff, @songxpu! 👏

How come a smiling face is "abuse"?

**Comment by halfgaar** [comment]
> > > According to the specification of [MQTTv5.0](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html):
> > 
> > 
> > > 
> > 
> > 
> > > […]
> > 
> > 
> > I don't understand why and who marked [this](https://github.com/halfgaar/FlashMQ/issues/104#issuecomment-2107364232) excellent, well-written comment by @songxpu as “abuse”. I know for a fact that @halfgaar _loves_ to receive such detailed bug reports. Excellent stuff, @songxpu! 👏
> 
> How come a smiling face is "abuse"?

That comment was marked as abuse. I unmarked it again. I'm not sure what happened there.

**Comment by halfgaar** [comment]
I had forgotten one mqtt5 property to check for 'more than once'. I fixed that. It's been pushed to master. A new release with this included will be made soon.

I decided to leave the ping/pong and suback codes unchanged. If you can show how it will actually be a problem, you can always open a new issue, or perhaps a [discussion](https://github.com/halfgaar/FlashMQ/discussions).

Thanks for the reports, and the good reproduction code :+1:. These 'not more than once' things were somewhere on my TODO list, so your report was good incentive.

**Comment by halfgaar** [comment]
> I noticed that when a client communicates with the broker using MQTT version 5.0, after the client sends a PUBLISH packet with QoS==1, the broker returns a PUBACK in MQTT version 3.1.1 format.
I believe that such protocol version downgrading is not expected behavior and may impact some clients.

Actually, from the spec:

> Byte 3 in the Variable Header is the PUBACK Reason Code. If the Remaining Length is 2, then there is no Reason Code and the value of 0x00 (Success) is used.

> Property length: If the Remaining Length is less than 4 there is no Property Length and the value of 0 is used.

**Comment by halfgaar** [comment]
The other issues are addressed in a branch. It needs some reviewing. Will push later.

**Comment by halfgaar** [comment]
> The other issues are addressed in a branch. It needs some reviewing. Will push later.

Fixes for those others have been pushed to master.
