### ISSUE TITLE
Feature request: Allow skipping tests that require a network connection

### ISSUE THREAD

**Issue by quinox** [halfgaar/FlashMQ#105]
I install FlashMQ using Portage, my package manager. I wanted to enable running the tests before replacing my system's FlashMQ but unfortunately this is currently not possible:

```
Tests run: 133. Passed: 128. Failed: 5 (of which 0 exceptions). Total assertions: 356423.

Failed tests:
 - testAsyncCurl
 - testDnsResolver
 - testDnsResolverDontCancel
 - testDnsResolverInvalid
 - testDnsResolverSecondQuery
```

Gentoo runs testcases in a sandbox and won't allow network connections, making it impossible to pass all the testcases.

They documented their reasons for this ([link](https://devmanual.gentoo.org/ebuild-writing/functions/src_test/index.html#tests-that-require-network-or-service-access)):

> 
> * the build may be running in an environment with no or restricted Internet access, and this must not cause the tests (build) to fail;
> * the Internet connection may be unstable (e.g. poor reception) in which case an interrupted connection or packet loss must not cause the tests to fail or hang, and it should not cause unnecessary delays;
> * the Internet connection may be running on a limited data plan in which case the additional network use may cause additional charges or other inconveniences to the user;
> * the remote network services used by the tests may become unavailable temporarily or permanently, causing unexpected test failures;
> * accessing remote sites always poses a privacy issue, and possibly a threat to security (e.g. through inadvertently exposing information about the system).

It would be nice if the FlashMQ testing framework has an easy way to skip the tests that require a network connection. Gentoo says the best solution would be to use mocking / replay data in the testcases but that sounds annoying to set up and maintain.

Attached my ebuild (just FYI, it's not really relevant to the feature request):
[flashmq-1.13.0.ebuild.txt](https://github.com/halfgaar/FlashMQ/files/15338427/flashmq-1.13.0.ebuild.txt)

**Comment by halfgaar** [comment]
I can do this. I'll do it along with making groups, because there are also many tests that don't require FlashMQ to run.

**Comment by halfgaar** [comment]
Fixed in master. Your ebuild refers to tags, so it won't work until the next release. Not sure when that is.
