### ISSUE TITLE
Ubuntu ARM builds

### ISSUE THREAD

**Issue by joelhaasnoot** [halfgaar/FlashMQ#107]
Any chance the Ubuntu repos could also publish builds for the ARM architecture?

**Comment by halfgaar** [comment]
That's a good point actually. It should be possible. 

I assume you're interested in arm64? I don't think it will be worthwhile to make arm32 builds.

**Comment by joelhaasnoot** [comment]
Yeah, sorry, arm64 builds. 
Hetzner has some nice small ARM nodes that are perfect for playing around with FlashMQ. I ended up building a package from source but harder to update.

**Comment by joelhaasnoot** [comment]
Yes, just tested it and it installs and runs perfectly - that closes the ticket. Thank you very much!
