### ISSUE TITLE
Logging to stdout

### ISSUE THREAD

**Issue by Bartarian** [halfgaar/FlashMQ#108]
I don't understand the documentation, there is a reference about logging to stdout, but looking at code I believe that's not possible to do that.

Manual:
https://github.com/halfgaar/FlashMQ/blob/b9b680cba7f78eef39aeac6b6e9b4181b06ea571/man/flashmq.conf.5#L74

**Comment by halfgaar** [comment]
The sentence is broken, but what it means, is that if you don't include a `log_file` config directive, the log output will go to stdout.

**Comment by halfgaar** [comment]
I fixed the documentation:

https://github.com/halfgaar/FlashMQ/commit/439e5d67140bf209ed37d573576068c2800c5249

The on-line man page won't be updated until the next release though.

I think that resolves the issue.
