### ISSUE TITLE
flashmq idle is consuming CPU

### ISSUE THREAD

**Issue by seb1k** [halfgaar/FlashMQ#114]
Hi !
Thanks for your amazing tool.

I'm using flashmq since +- 2 years now without issue.

I use it for less than 100 requests / hours. (let's say nothing)

My concern is about the CPU usage, when I started using it, it was less than 0.05% of my cpu. Just perfect !

After a few versions the CPU usage increased :(

Last year is was +-0.1% of the cpu (now much but still an increase without more usage)
Now it's +- 0.4% of the CPU for the same usage.

Are the developers are aware of this CPU increase?

![image](https://github.com/user-attachments/assets/7f265ecc-df89-402e-8175-1c974408c8c9)

Thanks.

**Comment by halfgaar** [comment]
That's a score out of 100%, so we're still talking about less than 1% CPU time? That is still very much in the noise region.

It's possible the various background tasks account for this. What I can tell you, is that this is not a linear relation. For servers that were under 50% CPU load, it will not have increased like that.

You can run `perf top -p $(pidof flashmq)` and see where the CPU goes.

**Comment by seb1k** [comment]
the result : 
![image](https://github.com/user-attachments/assets/7c4ca1d5-1bef-489e-b091-d5c2fe395f0c)

Server is a debian container on proxmox.
Yes, it's less than 1% CPU usage. So not a big issue, but the kind of issue that can lead me back to "mosquitto" :/

Thank you for your concern

**Comment by halfgaar** [comment]
A connoisseur of CPU cycles :)

There's already a [TODO in the code about this](https://github.com/halfgaar/FlashMQ/blob/fc27667faf5798db89bb7262f2b4d199a25c9a4d/backgroundworker.cpp#L11). I'll get to it, soonish.
