### ISSUE TITLE
Broker Does Not Return Protocol Error for Empty Topic with Topic Alias

### ISSUE THREAD

**Issue by bot973** [halfgaar/FlashMQ#120]
**Issue Description**
When sending a PUBLISH packet to the FlashMQ broker with an empty topic and a Topic Alias property, the broker does not return the expected DISCONNECT packet with a Protocol Error code. According to the MQTT v5.0 specification, using a Topic Alias with an empty topic before the alias is mapped should result in a Protocol Error.

**Steps to Reproduce**
 1. Start the FlashMQ broker with the following configuration with command `FlashMQ/build/flashmq -c FlashMQ/flashmq.conf`:
  ```
  log_file    FlashMQ/build/flashmq.log
  storage_dir FlashMQ/build
  thread_count 8
  allow_anonymous true
  ```
 2. Connect a client with MQTT v5.0 and send a PUBLISH packet containing:

-  Topic Name: empty (i.e., "")
-  Topic Alias: set to a non-zero value (e.g., 3)
Attached is a PCAP screenshot showing the communication sequence:
[topic-alias-flashmq.zip](https://github.com/user-attachments/files/17544130/topic-alias-flashmq.zip)

**Expected Behavior**
The broker should return a DISCONNECT packet with the reason code Protocol Error.

**Actual Behavior**
The broker does not return a DISCONNECT with a Protocol Error. Instead, it logs the following message:

> [T 1] Removing client '[ClientID='sub-test', username='', fd=28, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]'. Reason(s): Requesting topic alias ID (3) that wasn't set before., Hang up, Connection reset by peer

**Log Output**

> [INFO] [main] Setting rlimit nofile to 1000000
> [ERROR] [main] Setting ulimit nofile failed: 'Operation not permitted'. This means the default is used. Note. It's also subject to systemd's 'LimitNOFILE', which in turn is maxed to '/proc/sys/fs/nr_open', which can be set like 'sysctl fs.nr_open=15000000'
> [NOTICE] [main] 8 threads specified by 'thread_count'.
> [NOTICE] [main] Loading 'FlashMQ/build/retained.db'
> [NOTICE] [main] Loading 'FlashMQ/build/sessions.db'
> [NOTICE] [main] Starting FlashMQ version 1.17.1, release build with SSE4.2 support.
> [INFO] [main] Switching logging from stdout to logfile 'FlashMQ/build/flashmq.log'
> [NOTICE] [T 1] Client '[ClientID='sub-test', username='', fd=28, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]' logged in successfully
> [NOTICE] [T 1] Removing client '[ClientID='sub-test', username='', fd=28, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]'. Reason(s): Requesting topic alias ID (3) that wasn't set before., Hang up, Connection reset by peer

**Suggestion for Enhancement**
This may be considered as an enhancement to bring FlashMQ further in line with the MQTT v5.0 specification.

**Comment by halfgaar** [comment]
Thanks for the report, however I think there's something wrong with your test. The log shows 'Hang up, Connection reset by peer', which can only come from client action, so your client disappears before any other message can be created.

If we let `mosquitto_pub` wait between publishes (to avoid it being too fast with initiating disconnect itself) like the following, we do see disconnect code 148 (which means 'topic alias invalid):

```
( echo one; sleep 0.5; echo two) | mosquitto_pub -V 5 -D publish topic-alias 3 -t '' -l -h localhost -d
Client (null) sending CONNECT
Client lfCrurc6CBlY6hOZoehKWEz received CONNACK (0)
Client lfCrurc6CBlY6hOZoehKWEz sending PUBLISH (d0, q0, r0, m1, '(null)', ... (3 bytes))
Received DISCONNECT (148)
Error: Publish returned 4, disconnecting.
Error: The client is not currently connected.
```

This is the corresponding server log:

```
[2024-10-28 20:01:10.858] [NOTICE] [main] Accepting connection from: address='127.0.0.1', transport='TCP/Non-SSL', fd=28
[2024-10-28 20:01:10.859] [NOTICE] [T 0] Client '[ClientID='lfCrurc6CBlY6hOZoehKWEz', username='', fd=28, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]' logged in successfully
[2024-10-28 20:01:10.859] [NOTICE] [T 0] Removing client '[ClientID='lfCrurc6CBlY6hOZoehKWEz', username='', fd=28, keepalive=60s, transport='TCP/Non-SSL', address='127.0.0.1', prot=5.0, clean=1]'. Reason(s): Requesting topic alias ID (3) that wasn't set before.
```

Here you find the code where the exception is generated:

https://github.com/halfgaar/FlashMQ/blob/6d65c76db85704a4012752f1fe1bfc010ae57993/client.cpp#L571

I'll close the ticket, because I believe the current behavior is correct and in-line with your expected behavior.
