### ISSUE TITLE
Build with C++20 and strict compiler flags gives warnings

### ISSUE THREAD

**Issue by slavslavov** [halfgaar/FlashMQ#121]
I am building 1.17.2 with gcc (GCC) 14.2.1 20240801 (Red Hat 14.2.1-1), where C++20 is enabled and  many flags, like 
```
-Werror -pedantic-errors -Wall -Wextra -pedantic
```
And I get the following warning:
```
flashmq-src/nocopy.h:13:14: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
   13 |     NoCopy<T>() = default;
```

It is warning only, the executable builds and run but it will be good to fix it in one of the next releases

**Comment by halfgaar** [comment]
It even causes compilation errors on GCC C++20. How un-C++ to cause breakage...

I fixed it. My local master was a bit ahead, so a few more commits came along. I still want to subject some of that functionality to testing, so don't use in production. You can help test it with me, of course :)

**Comment by slavslavov** [comment]
Took me some time to realise the commit is in master but not in the latest tag. I don't get the warnings any more. But I ton't think you need `NoCopy<T>` in the other constructors and assignment operators. `NoCopy` works just fine

**Comment by halfgaar** [comment]
> Took me some time to realise the commit is in master but not in the latest tag.

Yeah, I had to do a quick release on 1.17.2, which became 1.17.3. I was not ready to take make a release of master.

> I don't get the warnings any more. But I don't think you need NoCopy<T> in the other constructors and assignment operators. NoCopy works just fine

It indeed derives it, but the type is ultimately `NoCopy<T>`, even the argument of the copy/move constructors. 

The error was that the constructor itself should not have a typed name, and therefore no type argument.
