### ISSUE TITLE
Support for Subscription Identifiers

### ISSUE THREAD

**Issue by smurfix** [halfgaar/FlashMQ#124]
FlashMQ doesn't support subscription identifiers. This is unfortunate, as: my client spends far too much time disentangling the topic and finding the subtask(s) that want the data.

What would it take to change that?

**Comment by halfgaar** [comment]
Ah, a negotiation :)

It looks doable. At first glance, a pickle is:

> Multiple Subscription Identifiers will be included if the publication is the result of a match to more than one subscription, in this case their order is not significant.

That's because FlashMQ doesn't merge overlapping subscriptions, allowed as per the standard:

> When Clients make subscriptions with Topic Filters that include wildcards, it is possible for a Client’s subscriptions to overlap so that a published message might match multiple filters. In this case the Server MUST deliver the message to the Client respecting the maximum QoS of all the matching subscriptions [MQTT-3.3.4-2]. **In addition, the Server MAY deliver further copies of the message, one for each additional matching subscription and respecting the subscription’s QoS in each case.**

So, the spec is a bit ambiguous here, but if all you need is giving a number to a subscribe packet and getting that number back in a matching message, shouldn't be that hard.

**Comment by smurfix** [comment]
Yep, that'd be very helpful. In fact, besides the speed-up it'd allow me to not deliver those non-merged packets twice (or more …) to each matching subscriber. I'd like to rip out the workaround I needed to prevent that from causing problems. ("Toggle" messages are an abomination.)

**Comment by halfgaar** [comment]
Are you able to compile yourself and test? I made a quick test branch:

https://github.com/halfgaar/FlashMQ/tree/wip-subscription-id

I tried to test quickly with mosquitto_sub, but that doesn't seem to have a format variable to print it.

It doesn't work yet for queued messages when clients are offline.

**Comment by smurfix** [comment]
Nice! Will do.

**Comment by smurfix** [comment]
Did you change something in your database? (My "normal" flashmq is 1.17.3, installed via `apt`.)

```dev:/src/flashmq$ sudo build/flashmq
[2024-11-09 13:46:58.396] [NOTICE] [main] Loading config. Reload: false.
[2024-11-09 13:46:58.396] [NOTICE] [main] Creating IPv4 non-SSL TCP listener on [0.0.0.0]:1883
[2024-11-09 13:46:58.396] [NOTICE] [main] Creating IPv6 non-SSL TCP listener on [::]:1883
[2024-11-09 13:46:58.396] [NOTICE] [main] Loading '/var/lib/flashmq/bridgenames.db'
[2024-11-09 13:46:58.399] [INFO] [main] Setting rlimit nofile to 1000000
[2024-11-09 13:46:58.399] [NOTICE] [main] 24 CPUs are detected, making as many threads. Use 'thread_count' setting to override.
[2024-11-09 13:46:58.399] [NOTICE] [main] Loading '/var/lib/flashmq/retained.db'
Can't specify PayloadFormatIndicator more than once
dev:/src/flashmq$ less /var/lib/flashmq/retained.db
```

**Comment by smurfix** [comment]
Yes that's what I mean.

**Comment by halfgaar** [comment]
Does it also happen on the current master?

**Comment by smurfix** [comment]
Yes.
Running a quick "git bisect" it says that the culprit is 0502d09f89dc938de2485defc8aca7e423a8c265

**Comment by smurfix** [comment]
I can send you my retained.db if necessary

**Comment by halfgaar** [comment]
That's actually a great test result,  unrelated to this.

Yes, can you send me the DB?

**Comment by smurfix** [comment]
Emailed. it's small. ;-)

**Comment by halfgaar** [comment]
Fixed. It was a small yet crucial bug.

I rebased and force pushed the subscription identifier branch.

**Comment by smurfix** [comment]
Tested, seems to work just fine. Thank you!

Coalescing multiple `Publish` packets with different subscription IDs into one would be nice but personally I can live with the overhead of not doing that, it's still way faster than scanning subscription lists in the client.

**Comment by halfgaar** [comment]
I'll polish it up some more (like write tests) before it goes into master. And there are some other caveats to deal with, like shared subscriptions. From what I gather from the spec, any new subscription on a subscription would set a new identifier, but it's basically unclear if that means shared ones as well.

> Coalescing multiple Publish packets with different subscription IDs into one would be nice but personally I can live with the overhead of not doing that, it's still way faster than scanning subscription lists in the client.

I'm very weary of putting such logic in the hottest path. If I ever do, it will likely be a setting.

**Comment by smurfix** [comment]
> From what I gather from the spec, any new subscription on a subscription would set a new identifier, but it's basically unclear if that means shared ones as well.

I assume that from the point of view of the client, `$share/foo/bar/baz` and `bar/baz` are distinct and get separate subscription IDs.

> I'm very weary of putting such logic in the hottest path. If I ever do, it will likely be a setting.

Fair enough. Not a priority; on systems with so much traffic that this matters, the subscriptions are likely to be done by different clients anyway.

**Comment by halfgaar** [comment]
> I assume that from the point of view of the client, $share/foo/bar/baz and bar/baz are distinct and get separate subscription IDs.

I meant that if you have two clients subscribing to `$share/foo/bar/baz`, they can each alter the subscription id.

It's also a bit weird that the subscription ID is a property on a subscribe packet that can contain multiple subscriptions. The spec says: "The Subscription Identifier is associated with any subscription created or modified as the result of this SUBSCRIBE packet." And there can be more than one in there.

**Comment by smurfix** [comment]
> I meant that if you have two clients subscribing to $share/foo/bar/baz, they can each alter the subscription id.

Umm I assume that the subscription ID is per-client, no matter the share state of the subscription, so one client won't be able to affect the other's subscription ID in any way.

> It's also a bit weird that the subscription ID is a property on a subscribe packet that can contain multiple subscriptions

AFAICT the subscription ID client's `Subscribe` packet tells the server that all of its subscriptions matching its pattern[s] are to be sent with this ID in the future instead of the ones that were previously associated with these patterns. (I have no idea why a client would ever want to replace subscription IDs but oh well.)

**Comment by halfgaar** [comment]
> Umm I assume that the subscription ID is per-client, no matter the share state of the subscription, so one client won't be able to affect the other's subscription ID in any way.

Actually, duh. Yes, you're right. And the data structure already works like this, so it will work out naturally.

**Comment by halfgaar** [comment]
I merged it to master. I still want to give it further testing though.
