### ISSUE TITLE
Errors while loading config should be handled

### ISSUE THREAD

**Issue by quinox** [halfgaar/FlashMQ#2]
This unexpectedly passes:
```
$ FlashMQ --test-config -c /dev/null
Config OK

$ ulimit -m 12345678
$ FlashMQ --test-config -c /dev/zero
Config OK
```

When I modify the code and call `infile.exceptions(std::ifstream::failbit | std::ifstream::badbit);` after opening `infile` they fail as expected:

```
$ FlashMQ --test-config -c /dev/null
basic_ios::clear: iostream error

$ FlashMQ --test-config -c /dev/zero
std::bad_alloc
```

**Comment by halfgaar** [comment]
Fixed in a general way, by checking for various types of invalid files or files that are too big.
