### ISSUE TITLE
Access to payload in auth plugin

### ISSUE THREAD

**Issue by halfgaar** [halfgaar/FlashMQ#33]
Review + test + think about https://github.com/slavslavov/FlashMQ/pull/1.

Was discussed [here](https://github.com/halfgaar/FlashMQ/discussions/23#discussioncomment-4944041).

**Comment by halfgaar** [comment]
My plan was to (try to) implement the read-only option. It mostly means stopping support for Ubuntu 18. I've been kind of sluggish, I know. But the time is about now to do it.

**Comment by slavslavov** [comment]
I have updated my draft PR to include the payload in the two F_flashmq_plugin_alter_XX functions. As with the previous commit it compiles but I haven't tested it.
These are breaking changes and I think your idea was to create plugin version 2 which will require more work to support many versions. If I can help with something - let me know.

**Comment by halfgaar** [comment]
My next few weeks are busy, but I did perform a quick upgrade of my PC here so I have C++ 17 available. I'll probably have some time to dive into this soon.

What needs testing (+test code) is whether the payload is visible in the plugin for:

* packets between MQTT3 and 5 clients.
* packets with different QoS levels between subscriber and publisher
* packets from internal publishes (like `$SYS`)
* Wills
* More?

**Comment by slavslavov** [comment]
The current implementation doesn't work and needs some small changes. I am in the middle of testing and will push a commit in my branch later today.

**Comment by halfgaar** [comment]
Note that my implementation works very differently from yours. You may want to make a new branch.

**Comment by slavslavov** [comment]
I had a look at your branch. The modifications I had to do in mine to make it work are coming closer to yours, although yours look more logical (you know your code better than anyone else :+1: ). I will stop updating my branch for now. Only one thing you may want to consider - std::string_view is really cheap to be passed by value and will perform better than passing by const ref)

**Comment by halfgaar** [comment]
> Only one thing you may want to consider - std::string_view is really cheap to be passed by value and will perform better than passing by const ref)

Can you elaborate on that? I thought that was only true for plain old data types. It would seem to be a simple 64 bit value as address is cheaper. Only if you benefit from locality of reference and/or CPU cache would a copy seem faster to me, but with a `string_view`, that's not possible anyway (it will most likely point far). 

Using a reference has the advantage of being faster when you don't use the payload. 

I tried to compare with Godbolt compiler explorer, but my test code was too synthetic and the optimizer threw it all away anyway...

**Comment by slavslavov** [comment]
I don't have personal experience measuring performance, it is all I have read. But when you google it you will read everywhere that `std::string_view` is faster to pass by value - it has only two members which fit well into the CPU registers, while with the reference you have one more indirection. Here are some links:
- https://stackoverflow.com/questions/58410793/passing-stdstring-view-by-reference - see the godbolt example in the accepted answer
- https://quuxplusone.github.io/blog/2021/11/09/pass-string-view-by-value/ - also contains godbolt link with some good explanations
- and last but not least all examples in the C++ Core Guidelines pass `std::stribg_view` by value - https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines

**Comment by slavslavov** [comment]
Yes, the payload is now available in the plugin. Thanks.

**Comment by halfgaar** [comment]
Is it weird that for an empty payload, we point it to outside the vector `bites` with a length 0 ... ?

**Comment by slavslavov** [comment]
It is an interesting one. I think it should be fine. `std::string_view` is not a zero based c-type string, it always relies on the length to be setup correctly. So with length of 0 it should be considered empty, no matter what the data points to.

**Comment by halfgaar** [comment]
Released.
