### ISSUE TITLE
How can I bridge FlashMQ to another MQTT broker?

### ISSUE THREAD

**Issue by MGasztold** [halfgaar/FlashMQ#59]
Hello,

Is it possible to configure a bridge to another MQTT broker so that my broker forwards messages from some selected topics to another broker? It is a core feature e.g. in mosquitto, see http://www.steves-internet-guide.com/mosquitto-bridge-configuration/

I cannot find any settings for that in the flashmq config file. Please help. Thanks.

**Comment by halfgaar** [comment]
It's being developed. I suspect it will take a few weeks more, give or take a few weeks :)

**Comment by halfgaar** [comment]
A branch with test version is here: https://github.com/halfgaar/FlashMQ/tree/bridge-public-beta

It can be compiled with `build.sh` or cmake. Are you able to?

Documentation can be seen [here](https://raw.githubusercontent.com/halfgaar/FlashMQ/bridge-public-beta/man/flashmq.conf.5.html), although Github renders it as plain text. The file can be downloaded and viewed.

The documentation can also be read by `man`:

```
cd /path/to/FlashMQ
cd man
man -l flashmq.conf.5
```

**Comment by huydoppa** [comment]
hey i come from zimbra forum . How can i contact you @halfgaar

**Comment by halfgaar** [comment]
My e-mail will do: wiebe@halfgaar.net

When you do, I'll delete these two messages not to confuse this issue.

**Comment by huydoppa** [comment]
i do plz check mail

**Comment by halfgaar** [comment]
I'm probably going to release this tomorrow as version 1.7.0. It will still be somewhat experimental, but when not using it, it doesn't hit that much new code, so should be safe enough to include.

**Comment by halfgaar** [comment]
Version 1.7.0 with bridge support was released. It will now enter the next testing phase, but seemed stable enough to include.
