### ISSUE TITLE
Build of 1.7.2 fails with gcc 13.1.1

### ISSUE THREAD

**Issue by slavslavov** [halfgaar/FlashMQ#68]
Building 1.7.2 fails with gcc (GCC) 13.1.1 20230511 (Red Hat 13.1.1-2). The error is that `std::string` is used in `globalstats.h` but the `<string>` header is not included.

Simply including `<string>` fixes the issue

**Comment by halfgaar** [comment]
Fixed. Still a one-shot fix though. Github Actions does not seem to have Ubuntu's newer than 22.04 to test newer compiler versions.
