### ISSUE TITLE
Add armhf and arm64 builds to the apt repo for Raspberry Pi OS

### ISSUE THREAD

**Issue by halfgaar** [halfgaar/FlashMQ#86]
Preliminary tests are good. Should be doable.

**Comment by Becker884** [comment]
I tried it on my Raspberry:

`Holen:3 http://repo.flashmq.org/apt bookworm InRelease [1.599 B]
Es wurden 1.599 B in 3 s geholt (482 B/s).
Paketlisten werden gelesen… Fertig
W: http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease: Schlüssel ist im veralteten Schlüsselbund trusted.gpg gespeichert (/etc/apt/trusted.gpg), siehe den Abschnitt MISSBILLIGUNG in apt-key(8) für Details.
N: Das Laden der konfigurierten Datei »main/binary-armhf/Packages« wird übersprungen, da das Depot »http://repo.flashmq.org/apt bookworm InRelease« die Architektur »armhf« nicht unterstützt.
N: Das Laden der konfigurierten Datei »main/binary-arm64/Packages« wird übersprungen, da das Depot »http://repo.flashmq.org/apt bookworm InRelease« die Architektur »arm64« nicht unterstützt.`

**Comment by halfgaar** [comment]
Hold your horses, it's not public yet :). It _may_ happen today, but not sure.

But that error is easily solved by the `curl` command on the [download page](https://www.flashmq.org/download/).

**Comment by Becker884** [comment]
the key error can be solved by: 
`sudo mv /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d/trusted.gpg`
it is a raspian bookworm problem.

> it's not public yet 
The headline suggested otherwise ¯\_(ツ)_/¯

**Comment by halfgaar** [comment]
> the key error can be solved by: `sudo mv /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d/trusted.gpg` it is a raspian bookworm problem.

I installed bookworm to test this. It seems unrelated to FlashMQ. FlashMQ's key is not stored in this deprecated fashion. Instead it uses the `signed-by` directive.

> 
> > it's not public yet
> 
> The headline suggested otherwise ¯_(ツ)_/¯

Well, the intention was to make an issue that describes the feature request. The description of the job still needs to be done/finished.

> 
> I prefer to install this way on RPi:
> 
> ```
> curl https://www.flashmq.org/wp-content/uploads/2021/10/flashmq-repo.gpg | sudo tee /etc/apt/keyrings/flashmq-repo.gpg
> 
> echo "deb [signed-by=/etc/apt/keyrings/flashmq-repo.gpg] http://repo.flashmq.org/apt bookworm main" | sudo tee /etc/apt/sources.list.d/flashmq.list
> ```

You mean you changed the location of the key? That's fine; perhaps better. I do wonder about your `tee` though. it will just garble your console.

**Comment by Becker884** [comment]
yes, the key problem has nothing to do with FlashMQ.

> You mean you changed the location of the key? That's fine; perhaps better. I do wonder about your tee though. it will just garble your console.

I just copied it from other manuals, for example Grafana, because /usr/share/keyrings doesn´t exist on raspian.
on my ubuntu VM I use /usr/share/keyrings.

**Comment by halfgaar** [comment]
I just did a fresh installation of bookworm to test with, and there was a `/usr/share/keyrings`. Hmm. 

I think the release is on its way.

**Comment by halfgaar** [comment]
The armhf and arm64 packages have been added, with the version upgrade to 1.10.0. Can you test?

**Comment by Becker884** [comment]
runs without problems

> I just did a fresh installation of bookworm to test with

raspian or debian ?

**Comment by halfgaar** [comment]
Excellent.

As for Bookworm, I used [Raspberry Pi OS](https://www.raspberrypi.com/software/). They say "Raspberry Pi OS (previously called Raspbian)".

**Comment by halfgaar** [comment]
Everything is done. Build infra is done. New version with arm debs released and announced.
